/* Shared, read-only DAG presentation. Data always comes from the caller. */
(function () {
  'use strict';
  const STAGES = ['todo','in-progress','implementation-complete','qa-passed','review-approved','done'];
  const empty = () => ({tasks:[],edges:[],waves:0,ready:[],critical_path:[]});
  function escape(s) { return String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); }
  function normalize(data) {
    data = data || empty();
    const ids = Object.fromEntries((data.tasks || []).map(t => [t.id, t.task_id || String(t.id).split(':').at(-1)]));
    return { tasks:(data.tasks||[]).map(t=>({...t,id:ids[t.id] || t.id,needs:(t.needs||[]).map(x=>ids[x]||x),contract_refs:(t.contract_refs||[]).map(({contract_ref,...x})=>x)})),
      edges:(data.edges||[]).map(e=>({from:ids[e.from]||e.from,to:ids[e.to]||e.to,unlocked:e.unlocked})), waves:data.waves||0,
      ready:(data.ready||[]).map(x=>ids[x]||x), critical_path:(data.critical_path||[]).map(x=>ids[x]||x) };
  }
  const css = `.ak-dag{height:100%;display:flex;flex-direction:column;background:var(--bg,#07090e);color:var(--text,#f1f5f9);font:12px var(--sans,system-ui);overflow:hidden}.ak-dag *{box-sizing:border-box}.ak-dag .bar,.ak-dag .foot{display:flex;align-items:center;gap:10px;padding:8px 12px;background:var(--bg-panel,#0d121f);border-color:var(--border,rgba(255,255,255,.08));border-style:solid}.ak-dag .bar{border-width:0 0 1px}.ak-dag .foot{border-width:1px 0 0}.ak-dag .spacer{flex:1}.ak-dag button{background:rgba(255,255,255,.04);border:1px solid var(--border,rgba(255,255,255,.08));border-radius:5px;color:var(--text-sub,#94a3b8);padding:5px 8px;cursor:pointer}.ak-dag button.on{background:var(--cyan,#38bdf8);color:#071018}.ak-dag .dot{display:inline-block;width:6px;height:6px;border-radius:50%;background:var(--green,#10b981)}.ak-dag .body{display:flex;min-height:0;flex:1}.ak-dag .canvas{flex:1;position:relative;overflow:hidden;cursor:grab;background-image:linear-gradient(rgba(255,255,255,.025) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.025) 1px,transparent 1px);background-size:32px 32px}.ak-dag .canvas.panning{cursor:grabbing}.ak-dag .inner{position:absolute;transform-origin:0 0}.ak-dag svg{position:absolute;overflow:visible;pointer-events:none}.ak-dag .lane{position:absolute;left:-160px;width:5000px;border-top:1px dashed var(--border,rgba(255,255,255,.08));color:var(--text-dim,#475569);font:10px var(--mono,monospace);padding-top:3px;text-align:right}.ak-dag .node{position:absolute;width:188px;border:1px solid var(--border,rgba(255,255,255,.08));border-radius:8px;background:var(--bg-card,rgba(19,27,46,.9));padding:8px;cursor:pointer}.ak-dag .node.ready{border-color:var(--amber,#f59e0b)}.ak-dag .node.blocked{border-color:var(--red,#f43f5e)}.ak-dag .node.selected{border-color:var(--cyan,#38bdf8);box-shadow:0 0 12px rgba(56,189,248,.35)}.ak-dag .node.dimmed,.ak-dag .edge-path.dimmed{opacity:.12}.ak-dag .id,.ak-dag .meta,.ak-dag .time{font:10px var(--mono,monospace);color:var(--text-dim,#475569)}.ak-dag .title{font-weight:600;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;margin:3px 0}.ak-dag .meta{display:flex;justify-content:space-between}.ak-dag .rail{display:flex;gap:2px;margin-top:7px}.ak-dag .rail i{display:block;flex:1;height:5px;background:rgba(255,255,255,.08);border-radius:2px}.ak-dag .rail i.filled{background:var(--green,#10b981)}.ak-dag .edge-path{fill:none}.ak-dag .edge-path.unlocked{stroke:var(--cyan,#38bdf8);stroke-width:2}.ak-dag .edge-path.locked{stroke:var(--text-dim,#475569);stroke-dasharray:4 4}.ak-dag .edge-path.critical{stroke:var(--amber,#f59e0b);stroke-width:3}.ak-dag aside{width:270px;border-left:1px solid var(--border,rgba(255,255,255,.08));padding:12px;overflow:auto}.ak-dag .kv{padding:4px 0;border-bottom:1px dashed var(--border,rgba(255,255,255,.08))}.ak-dag input{flex:1}.ak-dag .empty{color:var(--text-dim,#475569);padding:8px}`;
  function mount(host, options) {
    let data = normalize(options.data), selected = options.selected || null, critical = false, scrub = -1, pan={x:40,y:40}, zoom=1, panning;
    host.innerHTML = `<style>${css}</style><div class="ak-dag"><div class="bar"><b>Task DAG</b><span class="statWaves"></span><span class="statReady"></span><span class="spacer"></span><button id="btnCritical">Đường tới hạn</button><button id="btnLive" class="on"><i class="dot"></i> Bám hiện tại</button><button class="dagRefresh">↻ Refresh</button></div><div class="body"><div class="canvas"><div class="inner"><svg class="edges"></svg><div class="lanes"></div><div class="nodes"></div></div></div><aside><b>Chi tiết</b><div class="panel"><p class="empty">Click một task để xem dependency và trạng thái.</p></div></aside></div><div class="foot"><button class="playBtn">▶</button><input id="timeline" class="timeline" type="range" min="0" max="0" value="0"><span class="time">now</span></div></div>`;
    const $=s=>host.querySelector(s), canvas=$('.canvas'), inner=$('.inner'), nodes=$('.nodes'), edges=$('.edges'), lanes=$('.lanes'), panel=$('.panel'), timeline=$('.timeline');
    const events=()=>data.tasks.flatMap(t=>Object.entries(t.history||{}).map(([status,ts])=>({status,ts,id:t.id}))).sort((a,b)=>a.ts.localeCompare(b.ts));
    const byId=()=>Object.fromEntries(data.tasks.map(t=>[t.id,t]));
    // The status at `cut` is the LATEST one reached by then, not the furthest
    // along STAGES. Taking Math.max of the ladder indices meant a task that had
    // been rejected back to todo kept rendering at its high-water mark, and any
    // status outside the six-stage ladder -- blocked, superseded, cancelled --
    // was dropped by the `>=0` filter, so a blocked task rendered as
    // "in-progress" for the whole replay. stage may now be -1 (not a ladder
    // position), which simply leaves the progress rail empty.
    const effective=(t,cut)=>{if(!cut)return t;const seen=Object.entries(t.history||{}).filter(([,ts])=>ts<=cut).sort((a,b)=>String(a[1]).localeCompare(String(b[1])));if(!seen.length)return null;const status=seen[seen.length-1][0];return {...t,status,stage:STAGES.indexOf(status)};};
    const related = id => {
      const tasks = byId(), downstream = {};
      (data.edges || []).forEach(edge => (downstream[edge.from] ||= []).push(edge.to));
      const keep = new Set([id]), up = [...(tasks[id]?.needs || [])], down = [...(downstream[id] || [])];
      while (up.length) { const next = up.pop(); if (keep.has(next)) continue; keep.add(next); up.push(...(tasks[next]?.needs || [])); }
      while (down.length) { const next = down.pop(); if (keep.has(next)) continue; keep.add(next); down.push(...(downstream[next] || [])); }
      return keep;
    };
    function render() {
      const replay = events(), cut = scrub >= 0 ? replay[scrub]?.ts : null;
      const visible = data.tasks.map(task => effective(task, cut)).filter(Boolean);
      const ids = new Set(visible.map(task => task.id)), map = byId(), pos = {}, grouped = {};
      const laneList = [...new Set(visible.map(task => task.context || task.owner || '(no lane)'))];
      visible.forEach(task => { const lane = task.context || task.owner || '(no lane)'; ((grouped[lane] ||= {})[task.layer || 0] ||= []).push(task); });
      let y = 0; lanes.innerHTML = '';
      laneList.forEach(lane => { const groups = Object.values(grouped[lane]); const rows = Math.max(1, ...groups.map(group => group.length)); groups.forEach(group => group.forEach((task, row) => { pos[task.id] = {x:(task.layer || 0) * 236, y:y + row * 96}; })); lanes.insertAdjacentHTML('beforeend', `<div class="lane" style="top:${y}px">${escape(lane)}</div>`); y += rows * 96 + 22; });
      nodes.innerHTML = ''; const focus = selected ? related(selected) : null, criticalSet = new Set(data.critical_path || []);
      visible.forEach(task => { const point = pos[task.id], div = document.createElement('div'); const dimmed = (focus && !focus.has(task.id)) || (critical && !criticalSet.has(task.id)); div.className = `node ${task.ready && !cut ? 'ready' : ''} ${task.status === 'blocked' ? 'blocked' : ''} ${selected === task.id ? 'selected' : ''} ${dimmed ? 'dimmed' : ''}`; div.dataset.id = task.id; div.style.cssText = `left:${point.x}px;top:${point.y}px`; div.innerHTML = `<div class="id">${escape(task.id)} · L${task.layer ?? '?'}</div><div class="title">${escape(task.title)}</div><div class="meta"><span>${escape(task.owner)}</span><span>${escape(task.status)}</span></div><div class="rail">${Array.from({length:6}, (_, index) => `<i class="${(task.stage ?? STAGES.indexOf(task.status)) >= index ? 'filled' : ''}"></i>`).join('')}</div>`; div.onclick = () => { selected = selected === task.id ? null : task.id; options.onSelect?.(selected ? map[selected] : null); render(); }; nodes.append(div); });
      edges.innerHTML = (data.edges || []).filter(edge => ids.has(edge.from) && ids.has(edge.to)).map(edge => { const from = pos[edge.from], to = pos[edge.to], criticalEdge = (data.critical_path || []).some((id,index,path) => id === edge.from && path[index + 1] === edge.to), dimmed = (focus && (!focus.has(edge.from) || !focus.has(edge.to))) || (critical && !criticalEdge); return `<path class="edge-path ${edge.unlocked ? 'unlocked' : 'locked'} ${criticalEdge ? 'critical' : ''} ${dimmed ? 'dimmed' : ''}" d="M ${from.x + 188} ${from.y + 34} C ${(from.x + to.x + 188) / 2} ${from.y + 34}, ${(from.x + to.x + 188) / 2} ${to.y + 34}, ${to.x} ${to.y + 34}"/>`; }).join('');
      $('.statWaves').textContent = `waves: ${data.waves || 0}`; $('.statReady').textContent = `ready: ${(data.ready || []).length}`; timeline.max = Math.max(0, replay.length - 1); $('.time').textContent = cut || 'now';
      panel.innerHTML = selected && map[selected] ? `<div class="kv"><b>${escape(selected)}</b></div><div class="kv">${escape(map[selected].title)}</div><div class="kv">Needs: ${escape((map[selected].needs || []).join(', ')) || '—'}</div><div class="kv">Status: ${escape(map[selected].status)}</div>` : '<p class="empty">Click một task để xem dependency và trạng thái.</p>';
      inner.style.transform = `translate(${pan.x}px,${pan.y}px) scale(${zoom})`;
    }
    $('.dagRefresh').onclick=()=>options.onRefresh?.();$('#btnCritical').onclick=()=>{critical=!critical;$('#btnCritical').classList.toggle('on',critical);render()};$('#btnLive').onclick=()=>{scrub=-1;timeline.value=timeline.max;render()};timeline.oninput=()=>{scrub=+timeline.value>=+timeline.max?-1:+timeline.value;options.onReplayChange?.(scrub);render()};$('.playBtn').onclick=()=>{timeline.value=Math.min(+timeline.max,+timeline.value+1);timeline.dispatchEvent(new Event('input'))};canvas.onmousedown=e=>{if(e.target.closest('.node'))return;panning={x:e.clientX-pan.x,y:e.clientY-pan.y};canvas.classList.add('panning')};window.addEventListener('mousemove',e=>{if(panning){pan={x:e.clientX-panning.x,y:e.clientY-panning.y};inner.style.transform=`translate(${pan.x}px,${pan.y}px) scale(${zoom})`}});window.addEventListener('mouseup',()=>{panning=null;canvas.classList.remove('panning')});canvas.onwheel=e=>{e.preventDefault();zoom=Math.max(.4,Math.min(2,zoom+(e.deltaY>0?-.08:.08)));inner.style.transform=`translate(${pan.x}px,${pan.y}px) scale(${zoom})`};
    render(); return {setData(next){data=normalize(next);render()},selectTask(id){selected=id;render()},destroy(){host.innerHTML=''}};
  }
  window.AiKitDagView={mount,normalize};
})();
