"""Browser-level regression tests for .visualizer/dag.html.

The contract tests in test_visualizer_contract.py prove the engine still
emits the fields the page reads; these prove the page actually *renders*
them -- node/edge counts, the ready/blocked styling, click-to-focus
dimming, critical-path isolation, and the history scrubber -- and that it
does so with no console errors.

Requires playwright + a Chromium build. When either is unavailable the
whole module is skipped, so the dependency-free
`python -m unittest discover -s tests` job keeps working unchanged; CI runs
these in a separate job that installs the browser (see
.github/workflows/gates.yml).

Set DAG_BROWSER_TESTS=required to turn the skip into a failure -- that is
what the CI job does, so a broken install can't silently skip the suite.
"""
from __future__ import annotations

import contextlib
import http.server
import json
import os
import socket
import sys
import tempfile
import threading
import unittest
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
ENGINE_DIR = REPO_ROOT / ".ai" / "engine"
sys.path.insert(0, str(ENGINE_DIR))
import ai_kit  # noqa: E402

REQUIRED = os.environ.get("DAG_BROWSER_TESTS") == "required"

try:
    from playwright.sync_api import sync_playwright
    PLAYWRIGHT_IMPORT_ERROR = None
except ImportError as exc:  # pragma: no cover - environment dependent
    sync_playwright = None
    PLAYWRIGHT_IMPORT_ERROR = str(exc)


def chromium_path() -> str | None:
    """Locate the preinstalled Chromium, if the environment pins one."""
    explicit = os.environ.get("DAG_BROWSER_EXECUTABLE")
    if explicit:
        return explicit
    candidate = Path("/opt/pw-browsers/chromium")
    return str(candidate) if candidate.exists() else None


def setUpModule() -> None:
    if sync_playwright is None:
        message = f"playwright not installed ({PLAYWRIGHT_IMPORT_ERROR})"
        if REQUIRED:
            raise AssertionError(f"DAG_BROWSER_TESTS=required but {message}")
        raise unittest.SkipTest(message)


# Ignored console noise: the page is served standalone, so the browser's
# automatic /favicon.ico probe 404s, and index.html's Google Fonts <link>
# cannot resolve in a sandboxed/offline CI runner. Neither involves dag.html's
# own code; any other console error fails the test.
def is_real_error(text: str) -> bool:
    return not any(token in text for token in ("favicon", "404", "fonts.googleapis", "fonts.gstatic",
                                               "ERR_CONNECTION", "ERR_NAME_NOT_RESOLVED", "ERR_INTERNET"))


class QuietHandler(http.server.SimpleHTTPRequestHandler):
    def log_message(self, *args) -> None:  # silence per-request logging
        pass


class DagBrowserTests(unittest.TestCase):
    """Renders dag.html against a payload generated by the real engine."""

    @classmethod
    def setUpClass(cls) -> None:
        cls._tmp = tempfile.TemporaryDirectory()
        root = Path(cls._tmp.name)
        cls.serve_dir = root / "visualizer"
        cls.serve_dir.mkdir()

        # Build a real workflow through the engine rather than hand-writing
        # dag.json, so this also covers the generator end to end.
        for role in ("planner", "database", "backend", "frontend", "qa", "reviewer"):
            (root / ".ai" / "agents" / role).mkdir(parents=True, exist_ok=True)
        (root / ".ai" / "workflows" / "feature").mkdir(parents=True, exist_ok=True)
        (root / ".ai-config").mkdir(parents=True, exist_ok=True)

        saved = {
            name: getattr(ai_kit, name)
            for name in ("ROOT", "WORK", "STATE", "CURRENT", "EVENT_LOG", "VISUALIZER_DIR", "AUTO_ARTIFACT_GENERATION")
        }
        ai_kit.ROOT = root
        ai_kit.WORK = root / "unused"
        ai_kit.STATE = root / "unused" / "state" / "workflow.json"
        ai_kit.CURRENT = root / "unused" / "state" / "current.json"
        ai_kit.EVENT_LOG = root / "unused" / "logs" / "events.jsonl"
        ai_kit.VISUALIZER_DIR = cls.serve_dir
        ai_kit.AUTO_ARTIFACT_GENERATION = False
        try:
            state_file = root / "work" / "state" / "workflow.json"
            cls._build_workflow(str(state_file))
            cls._spread_event_timestamps(state_file)
            ai_kit._generate_visualizer_data(str(state_file))
        finally:
            for name, value in saved.items():
                setattr(ai_kit, name, value)

        payload = json.loads((cls.serve_dir / "dag.json").read_text(encoding="utf-8"))
        cls.payload = payload
        assert len(payload["tasks"]) == 6, payload
        for page in ("dag.html", "index.html", "app.js", "style.css"):
            (cls.serve_dir / page).write_bytes((REPO_ROOT / ".visualizer" / page).read_bytes())

        handler = type("Handler", (QuietHandler,), {"directory": str(cls.serve_dir)})
        handler.__init__ = lambda self, *a, **kw: QuietHandler.__init__(self, *a, directory=str(cls.serve_dir), **kw)
        cls.httpd = http.server.ThreadingHTTPServer(("127.0.0.1", 0), handler)
        cls.port = cls.httpd.server_address[1]
        cls.thread = threading.Thread(target=cls.httpd.serve_forever, daemon=True)
        cls.thread.start()

        cls._pw = sync_playwright().start()
        launch_kwargs = {}
        executable = chromium_path()
        if executable:
            launch_kwargs["executable_path"] = executable
        try:
            cls.browser = cls._pw.chromium.launch(**launch_kwargs)
        except Exception as exc:  # pragma: no cover - environment dependent
            cls._pw.stop()
            cls.httpd.shutdown()
            cls._tmp.cleanup()
            message = f"cannot launch chromium: {exc}"
            if REQUIRED:
                raise AssertionError(f"DAG_BROWSER_TESTS=required but {message}") from exc
            raise unittest.SkipTest(message) from exc

    @staticmethod
    def _spread_event_timestamps(state_file: Path) -> None:
        """Rewrite the fixture's event timestamps one minute apart.

        `now()` truncates to whole seconds, so a workflow built in-process
        lands every event in the same second and the replay scrubber has
        nothing to separate. Spreading them here keeps the replay assertions
        about the *page's* logic rather than about how fast the test ran.
        """
        state = json.loads(state_file.read_text(encoding="utf-8"))
        for index, item in enumerate(state["events"]):
            item["ts"] = f"2026-01-01T{index // 60:02d}:{index % 60:02d}:00Z"
        state_file.write_text(json.dumps(state, indent=2) + "\n", encoding="utf-8")

    @staticmethod
    def _build_workflow(state_file: str) -> None:
        import argparse

        def ns(**kw):
            base = dict(state=state_file, actor="planner", detail=None, evidence=None,
                        expected_revision=None, agent_id=None, context=None, epic=None)
            base.update(kw)
            return argparse.Namespace(**base)

        ai_kit.cmd_init(ns(title="browser test", workflow="feature", force=False))
        tasks = [
            ("T0", "Set up auth schema", "database", "plan", []),
            ("T1", "Build login API", "backend", "build", ["T0"]),
            ("T2", "Build signup API", "backend", "build", ["T0"]),
            ("T3", "Login UI", "frontend", "build", ["T1"]),
            ("T4", "Signup UI", "frontend", "build", ["T2"]),
            ("T5", "E2E auth tests", "qa", "verify", ["T3", "T4"]),
        ]
        for task_id, title, owner, phase, needs in tasks:
            ai_kit.cmd_add_task(ns(id=task_id, title=title, owner=owner, phase=phase,
                                   needs=needs, depends_on=[], acceptance=[["ok"]],
                                   files=[], tags=[]))
        # Drive T0 to done so at least one edge is unlocked and T1/T2 become ready.
        root = Path(state_file).parent.parent
        evidence_dir = root / "evidence"
        evidence_dir.mkdir(parents=True, exist_ok=True)
        for kind, key, value in (("qa", "status", "pass"), ("review", "verdict", "approve")):
            (evidence_dir / f"{kind}.json").write_text(
                json.dumps({"kind": kind, "task": "T0", key: value}), encoding="utf-8")
        ai_kit.cmd_transition(ns(id="T0", action="start", actor="database"))
        ai_kit.cmd_transition(ns(id="T0", action="complete", actor="database"))
        ai_kit.cmd_transition(ns(id="T0", action="qa-pass", actor="qa",
                                 evidence=[str(evidence_dir / "qa.json")]))
        ai_kit.cmd_transition(ns(id="T0", action="review-approve", actor="reviewer",
                                 evidence=[str(evidence_dir / "review.json")]))
        ai_kit.cmd_transition(ns(id="T0", action="close", actor="reviewer"))
        # Block T2 so the blocked styling has something to render.
        ai_kit.cmd_transition(ns(id="T2", action="block", actor="backend", detail="waiting on infra creds"))

    @classmethod
    def tearDownClass(cls) -> None:
        with contextlib.suppress(Exception):
            cls.browser.close()
        with contextlib.suppress(Exception):
            cls._pw.stop()
        with contextlib.suppress(Exception):
            cls.httpd.shutdown()
        with contextlib.suppress(Exception):
            cls._tmp.cleanup()

    @contextlib.contextmanager
    def page_at(self, path: str):
        errors: list[str] = []
        page = self.browser.new_page(viewport={"width": 1400, "height": 900})
        page.on("console", lambda m: errors.append(m.text) if m.type == "error" else None)
        page.on("pageerror", lambda e: errors.append(str(e)))
        page.goto(f"http://127.0.0.1:{self.port}/{path}")
        page.wait_for_timeout(700)
        try:
            yield page, errors
        finally:
            page.close()

    def test_renders_every_task_and_edge(self) -> None:
        with self.page_at("dag.html") as (page, errors):
            self.assertEqual(page.locator(".node").count(), len(self.payload["tasks"]))
            self.assertEqual(page.locator(".edge-path").count(), len(self.payload["edges"]))
            self.assertEqual([e for e in errors if is_real_error(e)], [])

    def test_no_two_nodes_overlap(self) -> None:
        """Regression: tasks sharing a lane *and* a layer used to render at
        identical coordinates, hiding one behind the other."""
        with self.page_at("dag.html") as (page, _errors):
            boxes = []
            for i in range(page.locator(".node").count()):
                box = page.locator(".node").nth(i).bounding_box()
                boxes.append((round(box["x"]), round(box["y"])))
            self.assertEqual(len(boxes), len(set(boxes)), f"overlapping nodes at {boxes}")

    def test_ready_and_blocked_styling_matches_payload(self) -> None:
        with self.page_at("dag.html") as (page, _errors):
            self.assertEqual(page.locator(".node.ready").count(), len(self.payload["ready"]))
            blocked = [t for t in self.payload["tasks"] if t["status"] == "blocked"]
            self.assertEqual(page.locator(".node.blocked").count(), len(blocked))

    def test_unlocked_edges_are_styled_distinctly(self) -> None:
        with self.page_at("dag.html") as (page, _errors):
            unlocked = [e for e in self.payload["edges"] if e["unlocked"]]
            self.assertEqual(page.locator(".edge-path.unlocked").count(), len(unlocked))
            self.assertEqual(page.locator(".edge-path.locked").count(),
                             len(self.payload["edges"]) - len(unlocked))

    def test_clicking_a_node_dims_unrelated_tasks(self) -> None:
        with self.page_at("dag.html") as (page, _errors):
            page.click('.node[data-id="T1"]')
            page.wait_for_timeout(200)
            # T1's ancestors/descendants are T0, T3, T5; T2 and T4 are unrelated.
            self.assertEqual(page.locator(".node.dimmed").count(), 2)
            page.click('.node[data-id="T1"]')
            page.wait_for_timeout(200)
            self.assertEqual(page.locator(".node.dimmed").count(), 0)

    def test_critical_path_toggle_isolates_the_chain(self) -> None:
        with self.page_at("dag.html") as (page, _errors):
            page.click("#btnCritical")
            page.wait_for_timeout(200)
            expected_dimmed = len(self.payload["tasks"]) - len(self.payload["critical_path"])
            self.assertEqual(page.locator(".node.dimmed").count(), expected_dimmed)

    def test_scrubbing_history_rewinds_task_progress(self) -> None:
        """At the earliest recorded timestamp T0 is back at `todo` (one rail
        segment filled); returning to live restores `done` (all six).

        Asserted on rail state rather than node count on purpose: `now()`
        truncates to whole seconds, so tasks created within the same second
        share a `todo` timestamp and cannot be separated on the scrubber --
        a real granularity limit of replay, not something the page can fix.
        """
        filled = lambda: page.locator('.node[data-id="T0"] .rail i.filled').count()
        with self.page_at("dag.html") as (page, _errors):
            self.assertEqual(filled(), 6, "T0 should start rendered as done")
            page.fill("#timeline", "0")
            page.dispatch_event("#timeline", "input")
            page.wait_for_timeout(200)
            self.assertEqual(filled(), 1, "scrubbed to the first event, T0 should be back at todo")
            self.assertGreater(page.locator(".node").count(), 0)
            page.click("#btnLive")
            page.wait_for_timeout(400)
            self.assertEqual(page.locator(".node").count(), len(self.payload["tasks"]))
            self.assertEqual(filled(), 6, "returning to live should restore T0 to done")

    def test_dag_tab_in_index_html_loads_the_page(self) -> None:
        with self.page_at("index.html") as (page, errors):
            page.click('.view-tab[data-view="dag"]')
            page.wait_for_timeout(600)
            frame = page.frame_locator("#viewDag iframe")
            self.assertEqual(frame.locator(".node").count(), len(self.payload["tasks"]))
            self.assertEqual([e for e in errors if is_real_error(e)], [])


if __name__ == "__main__":
    unittest.main()
